name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      is-a-release:
        description: Publish release? (Only works on master, and for untagged versions)
        type: boolean

permissions:
  contents: write

jobs:
  setup:
    name: Setup
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 21 ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          check-latest: true

  # Builds the projects and attempts to publish a release if the current project version
  # does not match any existing tags in the repository.
  build-and-release:
    name: Publish release
    needs: setup
    if: inputs.is-a-release && github.repository == 'Col-E/javafx-access-agent' && github.ref == 'refs/heads/master'
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required depth for JReleaser
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      # The project version extract NEEDS to have the gradle wrapper already downloaded.
      # So we have a dummy step here just to initialize it.
      - name: Download Gradle wrapper
        run: ./gradlew --version
      # Set environment variable for the project version: "var_to_set=$(command_to_run)" >> sink
      #  - For maven:  echo "PROJECT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      #  - For gradle: echo "PROJECT_VERSION=$(./gradlew properties | grep -Po '(?<=version: ).*')" >> $GITHUB_ENV
      - name: Extract project version to environment variable
        run: echo "PROJECT_VERSION=$(./gradlew properties | grep -Po '(?<=version\W ).*')" >> $GITHUB_ENV
      # Check if a tag exists that matches the current project version.
      # Write the existence state to the step output 'tagExists'.
      - name: Check the package version has corresponding Git tag
        id: tagged
        shell: bash
        run: |
          git show-ref --tags --verify --quiet -- "refs/tags/${{ env.PROJECT_VERSION }}" && echo "tagExists=1" >> $GITHUB_OUTPUT || echo "tagExists=0" >> $GITHUB_OUTPUT
          git show-ref --tags --verify --quiet -- "refs/tags/${{ env.PROJECT_VERSION }}" && echo "Tag for current version exists" || echo "Tag for current version does not exist"
      # If the tag could not be fetched, show a message and abort the job.
      # The wonky if logic is a workaround for: https://github.com/actions/runner/issues/1173
      - name: Abort if tag exists, or existence check fails
        if: ${{ false && steps.tagged.outputs.tagExists }}
        run: |
          echo "Output of 'tagged' step: ${{ steps.tagged.outputs.tagExists }}"
          echo "Failed to check if tag exists."
          echo "PROJECT_VERSION: ${{ env.PROJECT_VERSION }}"
          echo "Tags $(git tag | wc -l):"
          git tag
          git show-ref --tags --verify -- "refs/tags/${{ env.PROJECT_VERSION }}"
          exit 1
      # Run build to generate the release artifacts.
      # Tag does not exist AND trigger was manual. Deploy release artifacts!
      - name: Publish release
        run: ./gradlew publish jreleaserFullRelease
        env:
          JRELEASER_PROJECT_VERSION: ${{ env.PROJECT_VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_TOKEN }}
      # Upload JRelease debug log
      - name: JReleaser output
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jreleaser-release
          path: |
            build/jreleaser/trace.log
            build/jreleaser/output.properties